name: Complex

on: push

jobs:
  ubuntu:
    runs-on: ububtu-latest
    steps:
    - run: date
  macos:
    runs-on: macos-latest
    steps:
    - run: date
  windows:
    runs-on: windows-latest
    steps:
    - run: date
  custom:
    needs: [ubuntu, windows, macos]
    runs-on: ububtu-latest
    steps:
    - run: date
